# Generated by Django 5.2.17 on 2026-08-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['bedrooms', 'rent'], name='house_bedrooms_rent_idx'),
        ),
    ]
