# Generated by Django 5.2.17 on 2026-10-04 01:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_house_house_bedrooms_rent_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=2000)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=500)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_primary", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("FAVORITE", "Favorite"),
                            ("UNFAVORITE", "Unfavorite"),
                            ("CONTACT", "Contact"),
                        ],
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_preferences", models.JSONField()),
                ("result_property_ids", models.JSONField(default=list)),
                ("top_score", models.FloatField(blank=True, null=True)),
                ("total_matches", models.PositiveIntegerField(default=0)),
                ("budget_relaxed", models.BooleanField(default=False)),
                ("latency_ms", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "recommendation history",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "min_rent",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_rent",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "bedroom_mode",
                    models.CharField(
                        choices=[("exact", "Exact"), ("minimum", "Minimum")],
                        default="exact",
                        max_length=10,
                    ),
                ),
                ("furnished", models.BooleanField(blank=True, null=True)),
                ("parking", models.BooleanField(blank=True, null=True)),
                ("required_parking", models.BooleanField(default=False)),
                ("priority", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="house",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="house",
            name="available_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="city",
            field=models.CharField(default="Bangalore", max_length=100),
        ),
        migrations.AddField(
            model_name="house",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="house",
            name="floor",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-2),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listed_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("independent_house", "Independent house"),
                    ("villa", "Villa"),
                    ("studio", "Studio"),
                    ("penthouse", "Penthouse"),
                ],
                default="apartment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="security_deposit",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(120000000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="state",
            field=models.CharField(default="Karnataka", max_length=100),
        ),
        migrations.AddField(
            model_name="house",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("flagged", "Flagged for review"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="total_floors",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="area_sqft",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(100000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="bathrooms",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="bedrooms",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="rent",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000000),
                ]
            ),
        ),
        migrations.AddIndex(
            model_name="house",
            index=models.Index(fields=["status", "rent"], name="house_status_rent_idx"),
        ),
        migrations.AddIndex(
            model_name="house",
            index=models.Index(
                fields=["status", "-created_at"], name="house_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="house",
            constraint=models.CheckConstraint(
                condition=models.Q(("rent__gte", 0)), name="house_rent_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="house",
            constraint=models.CheckConstraint(
                condition=models.Q(("security_deposit__gte", 0)),
                name="house_deposit_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="house",
            constraint=models.CheckConstraint(
                condition=models.Q(("bedrooms__gte", 0), ("bedrooms__lte", 20)),
                name="house_bedrooms_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="house",
            constraint=models.CheckConstraint(
                condition=models.Q(("bathrooms__gte", 0), ("bathrooms__lte", 20)),
                name="house_bathrooms_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="house",
            constraint=models.CheckConstraint(
                condition=models.Q(("area_sqft__gt", 0)), name="house_area_positive"
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="rentals.house",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to="rentals.house",
            ),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="rentals.house",
            ),
        ),
        migrations.AddField(
            model_name="propertyinteraction",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="rentals.house",
            ),
        ),
        migrations.AddField(
            model_name="propertyinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recommendationhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendation_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "property"), name="unique_user_favorite"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyinteraction",
            index=models.Index(
                fields=["property", "interaction_type"],
                name="interaction_property_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyinteraction",
            index=models.Index(
                fields=["user", "-created_at"], name="interaction_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="rechistory_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationhistory",
            index=models.Index(fields=["created_at"], name="rechistory_created_idx"),
        ),
    ]
